---
name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        default: development
        type: choice
        options:
          - development
          - production
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

jobs:
  ci:
    name: CI
    uses: worgarside/github-config-files/.github/workflows/__ci.yml@main
    with:
      # Context Variables
      build-branch: '{{ build-branch }}'
      event-name: '{{ event_name }}'
      python-version: '{{ python_version }}'
      workflow-dispatch-env: '{{ workflow_dispatch_env }}'
      # Templated Variables
      build-type: '{{ build_type }}'
      node-build-directory: '{{ node_build_directory }}'
      path-to-__version__-file: '{{ path_to___version___file }}'
      pr-merged: '{{ pr_merged }}'
      unit-test: '{{ unit_test }}'
      update-pyproject-toml: '{{ update_pyproject_toml }}'
      update-json-file-path: '{{ update_json_file_path }}'
      update-yaml-file-path: '{{ update_yaml_file_path }}'
    secrets: inherit
