---
name: Run SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  run-sonarcloud-scan:
    name: Run SonarCloud Scan
    uses: worgarside/github-config-files/.github/workflows/__sonarcloud.yml@main
    with:
      branch: ${{ github.ref }}
    secrets: inherit
