---
worgarside/homeassistant:
  - .gitignore
  - .pre-commit-config.yaml
  - pyproject.toml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - utilities/dep_updater/

worgarside/wg-utilities@develop:
  - .gitignore
  - .pre-commit-config.yaml
  - pyproject.toml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - utilities/dep_updater/

worgarside/plant-monitor:
  - .gitignore
  - .pre-commit-config.yaml
  - pyproject.toml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - utilities/dep_updater/

worgarside/very-slow-movie-player:
  - .gitignore
  - .pre-commit-config.yaml
  - pyproject.toml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - utilities/dep_updater/

worgarside/wg-scripts:
  - .gitignore
  - .pre-commit-config.yaml
  - pyproject.toml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - utilities/dep_updater/

worgarside/smart-mini-crt-interface:
  - .gitignore
  - .pre-commit-config.yaml
  - pyproject.toml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - utilities/dep_updater/

