---
worgarside/homeassistant:
  - .gitignore
  - .pre-commit-config.yaml
  - pyproject.toml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - .github/workflows/pr_autoupdate.yaml

worgarside/wg-utilities@develop:
  - .gitignore
  - .pre-commit-config.yaml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - .github/workflows/pr_autoupdate.yaml

worgarside/plant-monitor:
  - .gitignore
  - .pre-commit-config.yaml
  - pyproject.toml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - utilities/dep_updater/
  - .github/workflows/pr_autoupdate.yaml

worgarside/very-slow-movie-player:
  - .gitignore
  - .pre-commit-config.yaml
  - pyproject.toml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - utilities/dep_updater/
  - .github/workflows/pr_autoupdate.yaml

worgarside/wg-scripts:
  - .gitignore
  - .pre-commit-config.yaml
  - pyproject.toml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - utilities/dep_updater/
  - .github/workflows/pr_autoupdate.yaml

worgarside/smart-mini-crt-interface:
  - .gitignore
  - .pre-commit-config.yaml
  - pyproject.toml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - utilities/dep_updater/
  - .github/workflows/pr_autoupdate.yaml

worgarside/useful-devops-scripts:
  - .gitignore
  - .pre-commit-config.yaml
  - pyproject.toml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - .github/workflows/pr_autoupdate.yaml

worgarside/json-resume@develop:
  - .gitignore
  - .pre-commit-config.yaml
  - pyproject.toml
  - .yamllint
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml

worgarside/led-matrix-now-playing:
  - .gitignore
  - .pre-commit-config.yaml
  - pyproject.toml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - utilities/dep_updater/
  - .github/workflows/pr_autoupdate.yaml
