---
worgarside/homeassistant:
  - .gitignore
  - .pre-commit-config.yaml
  - pyproject.toml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml

worgarside/wg-utilities@develop:
  - .gitignore
  - .pre-commit-config.yaml
  - pyproject.toml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml

worgarside/plant-monitor:
  - .gitignore
  - .pre-commit-config.yaml
  - pyproject.toml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml

worgarside/very-slow-movie-player:
  - .gitignore
  - .pre-commit-config.yaml
  - pyproject.toml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml

worgarside/wg-scripts:
  - .gitignore
  - .pre-commit-config.yaml
  - pyproject.toml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml

worgarside/smart-mini-crt-interface:
  - .gitignore
  - .pre-commit-config.yaml
  - pyproject.toml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml

