---
worgarside/homeassistant:
  - .gitignore
  - .pre-commit-config.yaml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - .github/workflows/pr_autoupdate.yaml
  - .github/repo_labels.yml
  - .github/workflows/manage_repo_labels.yml
  - .github/labeler.yml
  - .github/workflows/manage_pr_labels.yml
  - .github/workflows/run_sonarcloud_scan.yml

worgarside/wg-utilities@develop:
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - .github/repo_labels.yml
  - .github/workflows/manage_repo_labels.yml
  - .github/labeler.yml
  - .github/workflows/manage_pr_labels.yml

worgarside/plant-monitor:
  - .gitignore
  - .pre-commit-config.yaml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - utilities/dep_updater/
  - .github/workflows/pr_autoupdate.yaml
  - .github/repo_labels.yml
  - .github/workflows/manage_repo_labels.yml
  - .github/labeler.yml
  - .github/workflows/manage_pr_labels.yml
  - .github/workflows/run_sonarcloud_scan.yml

worgarside/very-slow-movie-player:
  - .gitignore
  - .pre-commit-config.yaml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - utilities/dep_updater/
  - .github/workflows/pr_autoupdate.yaml
  - .github/repo_labels.yml
  - .github/workflows/manage_repo_labels.yml
  - .github/labeler.yml
  - .github/workflows/manage_pr_labels.yml
  - .github/workflows/run_sonarcloud_scan.yml

worgarside/wg-scripts:
  - .gitignore
  - .pre-commit-config.yaml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - utilities/dep_updater/
  - .github/workflows/pr_autoupdate.yaml
  - .github/repo_labels.yml
  - .github/workflows/manage_repo_labels.yml
  - .github/labeler.yml
  - .github/workflows/manage_pr_labels.yml
  - .github/workflows/run_sonarcloud_scan.yml

worgarside/smart-mini-crt-interface:
  - .gitignore
  - .pre-commit-config.yaml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - utilities/dep_updater/
  - .github/workflows/pr_autoupdate.yaml
  - .github/repo_labels.yml
  - .github/workflows/manage_repo_labels.yml
  - .github/labeler.yml
  - .github/workflows/manage_pr_labels.yml
  - .github/workflows/run_sonarcloud_scan.yml

worgarside/useful-devops-scripts:
  - .gitignore
  - .pre-commit-config.yaml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - .github/workflows/pr_autoupdate.yaml
  - .github/repo_labels.yml
  - .github/workflows/manage_repo_labels.yml
  - .github/labeler.yml
  - .github/workflows/manage_pr_labels.yml
  - .github/workflows/run_sonarcloud_scan.yml

worgarside/json-resume@develop:
  - .gitignore
  - .pre-commit-config.yaml
  - .yamllint
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml

worgarside/led-matrix-now-playing:
  - .gitignore
  - .pre-commit-config.yaml
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - utilities/dep_updater/
  - .github/workflows/pr_autoupdate.yaml
  - .github/repo_labels.yml
  - .github/workflows/manage_repo_labels.yml
  - .github/labeler.yml
  - .github/workflows/manage_pr_labels.yml
  - .github/workflows/run_sonarcloud_scan.yml
