---

group:
  # All Repos
  - files:
      - .pylintrc
      - .github/CODEOWNERS
      - .github/dependabot.yml
      - .github/workflows/actionlint.yml
      - .github/workflows/auto_create_pr.yml
      - .github/workflows/dependabot_auto_merge.yml
      - .github/workflows/manage_pr_labels.yml
      - .github/workflows/manage_repo_labels.yml
      - .github/workflows/pr_autoupdate.yml
      - .github/workflows/pr_cleanup.yml
      - .github/workflows/run_sonarcloud_scan.yml
      - .github/workflows/set_pr_auto_merge.yml
    repos: |
      worgarside/addon-rss-log-feed
      worgarside/addon-yas-209-bridge
      worgarside/home-assistant@develop
      worgarside/led-matrix-now-playing
      worgarside/plant-monitor
      worgarside/python-template
      worgarside/smart-mini-crt-interface
      worgarside/useful-devops-scripts
      worgarside/very-slow-movie-player
      worgarside/wg-scripts
      worgarside/wg-utilities@develop

  # No Custom Labels
  - files:
      - .github/labeler.yml
      - .github/repo_labels.yml
    repos: |
      worgarside/addon-rss-log-feed
      worgarside/addon-yas-209-bridge
      worgarside/led-matrix-now-playing
      worgarside/plant-monitor
      worgarside/python-template
      worgarside/smart-mini-crt-interface
      worgarside/useful-devops-scripts
      worgarside/very-slow-movie-player
      worgarside/wg-scripts
      worgarside/wg-utilities@develop

  # Standard .gitignore
  - files:
      - .gitignore
    repos: |
      worgarside/addon-rss-log-feed
      worgarside/addon-yas-209-bridge
      worgarside/led-matrix-now-playing
      worgarside/plant-monitor
      worgarside/python-template
      worgarside/smart-mini-crt-interface
      worgarside/useful-devops-scripts
      worgarside/very-slow-movie-player
      worgarside/wg-scripts

  # Standard .yamllint
  - files:
      - .yamllint
    repos: |
      worgarside/addon-rss-log-feed
      worgarside/addon-yas-209-bridge
      worgarside/led-matrix-now-playing
      worgarside/plant-monitor
      worgarside/python-template
      worgarside/smart-mini-crt-interface
      worgarside/useful-devops-scripts
      worgarside/very-slow-movie-player
      worgarside/wg-scripts
