---
worgarside/home-assistant:
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/actionlint.yml
  - .github/workflows/dependabot_auto_merge.yml
  - .github/workflows/pr_autoupdate.yaml
  - .github/workflows/manage_repo_labels.yml
  - .github/workflows/manage_pr_labels.yml
  - .github/workflows/set_pr_auto_merge.yml
  - .github/workflows/run_sonarcloud_scan.yml
  - .pylintrc
  - .github/workflows/delete_pr_branch.yml
  - .github/workflows/auto_create_pr.yml
  - .github/CODEOWNERS

worgarside/wg-utilities@develop:
  - .github/dependabot.yml
  - .github/workflows/actionlint.yml
  - .github/workflows/dependabot_auto_merge.yml
  - .github/repo_labels.yml
  - .github/workflows/manage_repo_labels.yml
  - .github/labeler.yml
  - .github/workflows/manage_pr_labels.yml
  - .github/workflows/set_pr_auto_merge.yml
  - .github/workflows/delete_pr_branch.yml
  - .github/workflows/auto_create_pr.yml
  - .github/CODEOWNERS

worgarside/plant-monitor:
  - .gitignore
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/actionlint.yml
  - .github/workflows/dependabot_auto_merge.yml
  - utilities/dep_updater/
  - .github/workflows/pr_autoupdate.yaml
  - .github/repo_labels.yml
  - .github/workflows/manage_repo_labels.yml
  - .github/labeler.yml
  - .github/workflows/manage_pr_labels.yml
  - .github/workflows/set_pr_auto_merge.yml
  - .github/workflows/run_sonarcloud_scan.yml
  - .github/workflows/delete_pr_branch.yml
  - .github/workflows/auto_create_pr.yml
  - .github/CODEOWNERS

worgarside/very-slow-movie-player:
  - .gitignore
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/actionlint.yml
  - .github/workflows/dependabot_auto_merge.yml
  - utilities/dep_updater/
  - .github/workflows/pr_autoupdate.yaml
  - .github/repo_labels.yml
  - .github/workflows/manage_repo_labels.yml
  - .github/labeler.yml
  - .github/workflows/manage_pr_labels.yml
  - .github/workflows/set_pr_auto_merge.yml
  - .github/workflows/run_sonarcloud_scan.yml
  - .github/workflows/delete_pr_branch.yml
  - .github/workflows/auto_create_pr.yml
  - .github/CODEOWNERS

worgarside/wg-scripts:
  - .gitignore
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/actionlint.yml
  - .github/workflows/dependabot_auto_merge.yml
  - utilities/dep_updater/
  - .github/workflows/pr_autoupdate.yaml
  - .github/repo_labels.yml
  - .github/workflows/manage_repo_labels.yml
  - .github/labeler.yml
  - .github/workflows/manage_pr_labels.yml
  - .github/workflows/set_pr_auto_merge.yml
  - .github/workflows/run_sonarcloud_scan.yml
  - .github/workflows/delete_pr_branch.yml
  - .github/workflows/auto_create_pr.yml
  - .github/CODEOWNERS

worgarside/smart-mini-crt-interface:
  - .gitignore
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/actionlint.yml
  - .github/workflows/dependabot_auto_merge.yml
  - utilities/dep_updater/
  - .github/workflows/pr_autoupdate.yaml
  - .github/repo_labels.yml
  - .github/workflows/manage_repo_labels.yml
  - .github/labeler.yml
  - .github/workflows/manage_pr_labels.yml
  - .github/workflows/set_pr_auto_merge.yml
  - .github/workflows/run_sonarcloud_scan.yml
  - .github/workflows/delete_pr_branch.yml
  - .github/workflows/auto_create_pr.yml
  - .github/CODEOWNERS

worgarside/useful-devops-scripts:
  - .gitignore
  - .yamllint
  - .pylintrc
  - .github/dependabot.yml
  - .github/workflows/actionlint.yml
  - .github/workflows/dependabot_auto_merge.yml
  - .github/workflows/pr_autoupdate.yaml
  - .github/repo_labels.yml
  - .github/workflows/manage_repo_labels.yml
  - .github/labeler.yml
  - .github/workflows/manage_pr_labels.yml
  - .github/workflows/set_pr_auto_merge.yml
  - .github/workflows/run_sonarcloud_scan.yml
  - .github/workflows/delete_pr_branch.yml
  - .github/CODEOWNERS

worgarside/json-resume@develop:
  - .gitignore
  - .yamllint
  - .github/workflows/actionlint.yml
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - .github/workflows/delete_pr_branch.yml
  - .github/CODEOWNERS

worgarside/led-matrix-now-playing:
  - .gitignore
  - .yamllint
  - .pylintrc
  - .github/workflows/actionlint.yml
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - utilities/dep_updater/
  - .github/workflows/pr_autoupdate.yaml
  - .github/repo_labels.yml
  - .github/workflows/manage_repo_labels.yml
  - .github/labeler.yml
  - .github/workflows/manage_pr_labels.yml
  - .github/workflows/set_pr_auto_merge.yml
  - .github/workflows/run_sonarcloud_scan.yml
  - .github/workflows/delete_pr_branch.yml
  - .github/workflows/auto_create_pr.yml
  - .github/CODEOWNERS

worgarside/python-template:
  - .gitignore
  - .yamllint
  - .pylintrc
  - .github/workflows/actionlint.yml
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - .github/workflows/pr_autoupdate.yaml
  - .github/repo_labels.yml
  - .github/workflows/manage_repo_labels.yml
  - .github/labeler.yml
  - .github/workflows/manage_pr_labels.yml
  - .github/workflows/set_pr_auto_merge.yml
  - .github/workflows/run_sonarcloud_scan.yml
  - .github/workflows/delete_pr_branch.yml
  - .github/workflows/auto_create_pr.yml
  - .github/CODEOWNERS

worgarside/addon-rss-log-feed:
  - .gitignore
  - .yamllint
  - .pylintrc
  - .github/workflows/actionlint.yml
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - .github/workflows/pr_autoupdate.yaml
  - .github/repo_labels.yml
  - .github/workflows/manage_repo_labels.yml
  - .github/labeler.yml
  - .github/workflows/manage_pr_labels.yml
  - .github/workflows/set_pr_auto_merge.yml
  - .github/workflows/run_sonarcloud_scan.yml
  - .github/workflows/delete_pr_branch.yml
  - .github/workflows/auto_create_pr.yml
  - .github/CODEOWNERS

worgarside/addon-yas-209-bridge:
  - .gitignore
  - .yamllint
  - .pylintrc
  - .github/workflows/actionlint.yml
  - .github/dependabot.yml
  - .github/workflows/dependabot_auto_merge.yml
  - .github/workflows/pr_autoupdate.yaml
  - .github/repo_labels.yml
  - .github/workflows/manage_repo_labels.yml
  - .github/labeler.yml
  - .github/workflows/manage_pr_labels.yml
  - .github/workflows/set_pr_auto_merge.yml
  - .github/workflows/run_sonarcloud_scan.yml
  - .github/workflows/delete_pr_branch.yml
  - .github/workflows/auto_create_pr.yml
  - .github/CODEOWNERS
