---
default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/worgarside/pre-commit-hooks-dependency-sync
    rev: 1.1.2
    hooks:
      - id: sync-additional-dependencies

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: local
    hooks:
      - id: generate-readme
        name: Generate README
        entry: python utilities/readme/generate_readme.py
        language: python
        files: ^$
        always_run: true
        additional_dependencies:
          - pydantic==2.8.2
          - pyyaml==6.0.2

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.1
    hooks:
      - id: actionlint
        args:
          - -ignore
          - SC2129
          - -shellcheck
          - ''

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=1000
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args:
          - --pytest-test-first
      - id: pretty-format-json
        args:
          - --no-sort-keys
          - --autofix
          - --indent
          - '2'
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args:
          - --mapping
          - '2'
          - --sequence
          - '4'
          - --offset
          - '2'
          - --width
          - '4096'

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args:
          - --format
          - parsable
          - --strict

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        args:
          - --strict
          - --show-error-codes
        additional_dependencies:
          - pydantic==2.8.2
          - types-PyYAML
          - httpx==0.27.0
          - wg-utilities==5.16.0

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
