---
name: ESLint

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  eslint:
    name: ESLint
    runs-on:
      - self-hosted
      - linux
      - x64
      - cc
      - iac
      - opentofu
    steps:
      - name: Clone Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: npm
          cache-dependency-path: item_warehouse_website/package-lock.json
          node-version: '18'

      - name: Install Dependencies
        run: cd item_warehouse_website && npm ci

      - name: Run ESLint
        run: cd item_warehouse_website && npm run lint
