---
name: actionlint

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  actionlint:
    name: Lint GHAs
    uses: worgarside/github-config-files/.github/workflows/__actionlint.yml@main
