---
name: 'CI: Validation & Deployment'

on:
  push:
    branches:
      - main

jobs:
  ci-validation:
    name: 'CI: Validation'
    uses: worgarside/github-config-files/.github/workflows/__ci_validation.yml@main
    with:
      build-branch: '{{ build_branch }}'
      build-type: '{{ build_type }}'
      node-build-directory: '{{ node_build_directory }}'
      python-version: '{{ python_version }}'
      unit-test: '{{ unit_test }}'
    secrets: inherit

  ci-deployment:
    name: 'CI: Deployment'
    needs:
      - ci-validation
    if: |
      needs.ci-validation.outputs.release-tag != 'null' &&
      needs.ci-validation.outputs.release-tag != github.event.head_commit.message
    permissions:
      id-token: write
    uses: worgarside/github-config-files/.github/workflows/__ci_deployment.yml@main
    with:
      build-branch: '{{ build_branch }}'
      build-type: '{{ build_type }}'
      deploy-to: '{{ deploy_to }}'
      deploy-documentation: '{{ deploy_documentation }}'
      node-build-directory: '{{ node_build_directory }}'
      path-to-__version__-file: '{{ path_to___version___file }}'
      python-version: '{{ python_version }}'
      release-tag: '{{ release_tag }}'
      unit-test: '{{ unit_test }}'
      update-pyproject-toml: '{{ update_pyproject_toml }}'
      update-json-file-path: '{{ update_json_file_path }}'
      update-yaml-file-path: '{{ update_yaml_file_path }}'
    secrets: inherit
