---
name: CodSpeed Benchmarks

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CACHE_FILE: poetry.lock

jobs:
  benchmarks:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    if: '{{ condition }}'
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '{{ python_version }}'

      - name: Load cached .local
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: dotlocal

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load Cached Venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: '{{ cache_key }}'

      - name: Install Dependencies
        run: poetry install --sync

      - name: Run Benchmarks
        uses: CodSpeedHQ/action@v2
        with:
          token: '{{ token }}'
          run: poetry run pytest --codspeed
