---
# yamllint disable rule:line-length

group:
  # All Repos
  - files:
      - .gitignore
      - .github/CODEOWNERS
      - .github/dependabot.yml
      - source: gha_sync/workflows/all
        dest: .github/workflows/
        deleteOrphaned: true
    repos: |
      worgarside/home-assistant-appdaemon

  # This is every repo apart from `addon-item-warehouse-website` (Doesn't use Pylint)
  - files:
      - .pylintrc
    repos: |
      worgarside/home-assistant-appdaemon

  # No Custom Labels
  # The only exclusion is `home-assistant`, which has its own repo_labels.yml:
  # https://github.com/worgarside/home-assistant/blob/main/.github/repo_labels.yml
  - files:
      - .github/labeler.yml
      - .github/repo_labels.yml
    repos: |
      worgarside/home-assistant-appdaemon

  # Standard .yamllint
  - files:
      - .yamllint
    repos: |
      worgarside/home-assistant-appdaemon

  # Release Notes Template
  - files:
      - source: gha_sync/configs/release-drafter.yml
        dest: .github/release-drafter.yml
    repos: |
      worgarside/home-assistant-appdaemon

  # Standard release with version bump in pyproject.toml
  - files:
      - source: gha_sync/workflows/template/ci.template.yml
        dest: .github/workflows/ci.yml
        template:
          build_branch: ${{ github.ref }}
          event_name: ${{ github.event_name }}
          pr_merged: ${{ github.event.pull_request.merged }}
          workflow_dispatch_env: ${{ inputs.environment }}
          build_type: python
          python_version: '3.11'
          update_pyproject_toml: 'true'
    repos: |
      worgarside/home-assistant-appdaemon
