---
# yamllint disable rule:line-length

group:
  # All Repos
  - files:
      - .gitignore
      - .github/CODEOWNERS
      - .github/dependabot.yml
      - source: gha_sync/workflows/all
        dest: .github/workflows/
        deleteOrphaned: true
    repos: |
      worgarside/addon-item-warehouse-api
      worgarside/addon-item-warehouse-website
      worgarside/addon-rss-log-feed
      worgarside/addon-yas-209-bridge
      worgarside/home-assistant
      worgarside/home-assistant-config-validator
      worgarside/led-matrix-now-playing
      worgarside/plant-monitor
      worgarside/python-template
      worgarside/smart-mini-crt-interface
      worgarside/very-slow-movie-player
      worgarside/wg-scripts
      worgarside/wg-utilities

  # This is every repo apart from `wg-utilities` (Runs SonarCloud after UTs)
  - files:
      - source: gha_sync/workflows/run_sonarcloud_scan.yml
        dest: .github/workflows/run_sonarcloud_scan.yml
    repos: |
      worgarside/addon-item-warehouse-api
      worgarside/addon-item-warehouse-website
      worgarside/addon-rss-log-feed
      worgarside/addon-yas-209-bridge
      worgarside/home-assistant
      worgarside/home-assistant-config-validator
      worgarside/led-matrix-now-playing
      worgarside/plant-monitor
      worgarside/python-template
      worgarside/smart-mini-crt-interface
      worgarside/very-slow-movie-player
      worgarside/wg-scripts

  # This is every repo apart from `addon-item-warehouse-website` (Doesn't use Pylint)
  - files:
      - .pylintrc
    repos: |
      worgarside/addon-item-warehouse-api
      worgarside/addon-rss-log-feed
      worgarside/addon-yas-209-bridge
      worgarside/home-assistant
      worgarside/home-assistant-config-validator
      worgarside/led-matrix-now-playing
      worgarside/plant-monitor
      worgarside/python-template
      worgarside/smart-mini-crt-interface
      worgarside/very-slow-movie-player
      worgarside/wg-scripts
      worgarside/wg-utilities

  # No Custom Labels
  # The only exclusion is `home-assistant`, which has its own repo_labels.yml:
  # https://github.com/worgarside/home-assistant/blob/develop/.github/repo_labels.yml
  - files:
      - .github/labeler.yml
      - .github/repo_labels.yml
    repos: |
      worgarside/addon-item-warehouse-api
      worgarside/addon-item-warehouse-website
      worgarside/addon-rss-log-feed
      worgarside/addon-yas-209-bridge
      worgarside/home-assistant-config-validator
      worgarside/led-matrix-now-playing
      worgarside/plant-monitor
      worgarside/python-template
      worgarside/smart-mini-crt-interface
      worgarside/very-slow-movie-player
      worgarside/wg-scripts
      worgarside/wg-utilities

  # Standard .yamllint
  - files:
      - .yamllint
    repos: |
      worgarside/addon-item-warehouse-api
      worgarside/addon-rss-log-feed
      worgarside/addon-yas-209-bridge
      worgarside/home-assistant-config-validator
      worgarside/led-matrix-now-playing
      worgarside/plant-monitor
      worgarside/python-template
      worgarside/smart-mini-crt-interface
      worgarside/very-slow-movie-player
      worgarside/wg-scripts

  # Standard Release Notes Template
  - files:
      - source: gha_sync/configs/release-drafter.yml
        dest: .github/release-drafter.yml
    repos: |
      worgarside/addon-item-warehouse-api
      worgarside/addon-item-warehouse-website
      worgarside/addon-rss-log-feed
      worgarside/addon-yas-209-bridge
      worgarside/home-assistant-config-validator

  # Publish Release with no build
  - files:
      - source: gha_sync/workflows/publish_release.yml
        dest: .github/workflows/publish_release.yml
    repos: |
      worgarside/addon-item-warehouse-api
      worgarside/addon-rss-log-feed
      worgarside/addon-yas-209-bridge
      worgarside/home-assistant
      worgarside/home-assistant-config-validator

  # Standard release with version bump in pyproject.toml
  - files:
      - source: gha_sync/workflows/create_new_release.yml
        dest: .github/create_new_release.yml
    repos: |
      worgarside/home-assistant
      worgarside/home-assistant-config-validator

worgarside/addon-item-warehouse-api:
  - source: gha_sync/workflows/create_new_release.template.yml
    dest: .github/workflows/create_new_release.yml
    template:
      config_path: item_warehouse_api/config.yaml
      secrets_WORGARSIDE_DEV_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}

worgarside/addon-item-warehouse-website:
  - source: gha_sync/workflows/repo/addon-item-warehouse-website/create_new_release.template.yml
    dest: .github/workflows/create_new_release.yml
    template:
      config_path: item_warehouse_website/config.yaml
      secrets_WORGARSIDE_DEV_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
  - source: gha_sync/workflows/repo/addon-item-warehouse-website/
    dest: .github/workflows/
    deleteOrphaned: true
    # Excluded to allow above templating
    exclude: create_new_release.template.yml

worgarside/addon-rss-log-feed:
  - source: gha_sync/workflows/create_new_release.template.yml
    dest: .github/workflows/create_new_release.yml
    template:
      config_path: rss_log_feed/config.yaml
      secrets_WORGARSIDE_DEV_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}

worgarside/addon-yas-209-bridge:
  - source: gha_sync/workflows/create_new_release.template.yml
    dest: .github/workflows/create_new_release.yml
    template:
      config_path: yas_209_bridge/config.yaml
      secrets_WORGARSIDE_DEV_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}

worgarside/home-assistant:
  - source: gha_sync/workflows/repo/home-assistant/
    dest: .github/workflows/
    deleteOrphaned: true

worgarside/wg-utilities:
  - source: gha_sync/workflows/repo/wg-utilities
    dest: .github/workflows/
    deleteOrphaned: true
