---

group:
  # All Repos
  - files:
      - .pylintrc
      - .github/CODEOWNERS
      - .github/dependabot.yml
      - source: gha_sync/workflows/all_repos/
        dest: .github/workflows/
        deleteOrphaned: true
    repos: |
      worgarside/addon-item-warehouse
      worgarside/addon-rss-log-feed
      worgarside/addon-yas-209-bridge
      worgarside/home-assistant
      worgarside/home-assistant-config-validator
      worgarside/led-matrix-now-playing
      worgarside/plant-monitor
      worgarside/python-template
      worgarside/smart-mini-crt-interface
      worgarside/useful-devops-scripts
      worgarside/very-slow-movie-player
      worgarside/wg-scripts
      worgarside/wg-utilities

  # No Custom Labels
  - files:
      - .github/labeler.yml
      - .github/repo_labels.yml
    repos: |
      worgarside/addon-item-warehouse
      worgarside/addon-rss-log-feed
      worgarside/addon-yas-209-bridge
      worgarside/home-assistant-config-validator
      worgarside/led-matrix-now-playing
      worgarside/plant-monitor
      worgarside/python-template
      worgarside/smart-mini-crt-interface
      worgarside/useful-devops-scripts
      worgarside/very-slow-movie-player
      worgarside/wg-scripts
      worgarside/wg-utilities

  # Standard .gitignore
  - files:
      - .gitignore
    repos: |
      worgarside/addon-item-warehouse
      worgarside/addon-rss-log-feed
      worgarside/addon-yas-209-bridge
      worgarside/home-assistant-config-validator
      worgarside/led-matrix-now-playing
      worgarside/plant-monitor
      worgarside/python-template
      worgarside/smart-mini-crt-interface
      worgarside/useful-devops-scripts
      worgarside/very-slow-movie-player
      worgarside/wg-scripts

  # Standard .yamllint
  - files:
      - .yamllint
    repos: |
      worgarside/addon-item-warehouse
      worgarside/addon-rss-log-feed
      worgarside/addon-yas-209-bridge
      worgarside/home-assistant-config-validator
      worgarside/led-matrix-now-playing
      worgarside/plant-monitor
      worgarside/python-template
      worgarside/smart-mini-crt-interface
      worgarside/useful-devops-scripts
      worgarside/very-slow-movie-player
      worgarside/wg-scripts

  # Versioned Repos
  - files:
      - source: gha_sync/workflows/versioned_repos
        dest: .github/workflows/
        deleteOrphaned: true
    repos: |
      worgarside/addon-item-warehouse
      worgarside/addon-rss-log-feed
      worgarside/addon-yas-209-bridge
      worgarside/home-assistant
      worgarside/home-assistant-config-validator
      worgarside/wg-utilities
