---

group:
  # All Repos
  - files:
      - .pylintrc
      - .github/CODEOWNERS
      - .github/dependabot.yml
      - source: gha_sync/workflows/all_repos
        dest: .github/workflows/
        # deleteOrphaned: true
    repos: |
      worgarside/addon-item-warehouse-api
      worgarside/addon-item-warehouse-website
      worgarside/addon-rss-log-feed
      worgarside/addon-yas-209-bridge
      worgarside/home-assistant
      worgarside/home-assistant-config-validator
      worgarside/led-matrix-now-playing
      worgarside/plant-monitor
      worgarside/python-template
      worgarside/smart-mini-crt-interface
      worgarside/useful-devops-scripts
      worgarside/very-slow-movie-player
      worgarside/wg-scripts

  # All normal workflows minus SonarCloud (run after UTs)
  - files:
      - .pylintrc
      - .github/CODEOWNERS
      - .github/dependabot.yml
      - source: gha_sync/workflows/all_repos
        dest: .github/workflows/
        exclude: run_sonarcloud_scan.yml
        # deleteOrphaned: true
    repos: |
      worgarside/wg-utilities

  # No Custom Labels
  - files:
      - .github/labeler.yml
      - .github/repo_labels.yml
    repos: |
      worgarside/addon-item-warehouse-api
      worgarside/addon-item-warehouse-website
      worgarside/addon-rss-log-feed
      worgarside/addon-yas-209-bridge
      worgarside/home-assistant-config-validator
      worgarside/led-matrix-now-playing
      worgarside/plant-monitor
      worgarside/python-template
      worgarside/smart-mini-crt-interface
      worgarside/useful-devops-scripts
      worgarside/very-slow-movie-player
      worgarside/wg-scripts
      worgarside/wg-utilities

  # Standard .gitignore
  - files:
      - .gitignore
    repos: |
      worgarside/addon-item-warehouse-api
      worgarside/addon-item-warehouse-website
      worgarside/addon-rss-log-feed
      worgarside/addon-yas-209-bridge
      worgarside/home-assistant-config-validator
      worgarside/led-matrix-now-playing
      worgarside/plant-monitor
      worgarside/python-template
      worgarside/smart-mini-crt-interface
      worgarside/useful-devops-scripts
      worgarside/very-slow-movie-player
      worgarside/wg-scripts

  # Standard .yamllint
  - files:
      - .yamllint
    repos: |
      worgarside/addon-item-warehouse-api
      worgarside/addon-item-warehouse-website
      worgarside/addon-rss-log-feed
      worgarside/addon-yas-209-bridge
      worgarside/home-assistant-config-validator
      worgarside/led-matrix-now-playing
      worgarside/plant-monitor
      worgarside/python-template
      worgarside/smart-mini-crt-interface
      worgarside/useful-devops-scripts
      worgarside/very-slow-movie-player
      worgarside/wg-scripts

  # Versioned Repos
  - files:
      - source: gha_sync/workflows/versioned_repos
        dest: .github/workflows/
        # deleteOrphaned: true
      - source: gha_sync/configs/versioned_repos
        dest: .github/
        # Home Assistant has its own template
        exclude: |
          release-drafter.yml
    repos: |
      worgarside/home-assistant
      worgarside/home-assistant-config-validator

  # PyPi Repos (Versioned + Publish to PyPi)
  - files:
      - source: gha_sync/workflows/pypi_repos
        dest: .github/workflows/
      - source: gha_sync/configs/versioned_repos
        dest: .github/
        # deleteOrphaned: true
    repos: |
      worgarside/wg-utilities

worgarside/addon-item-warehouse-api:
  - source: gha_sync/workflows/addon_repos/create_new_release.yml
    dest: .github/workflows/create_new_release.yml
    template:
      config_path: item_warehouse_api/config.yaml
      secrets_WORGARSIDE_DEV_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
  - source: gha_sync/workflows/versioned_repos
    dest: .github/workflows/
    exclude: |
      create_new_release.yml
  - source: gha_sync/configs/versioned_repos
    dest: .github/

worgarside/addon-item-warehouse-website:
  - source: gha_sync/workflows/addon_repos/create_new_release.yml
    dest: .github/workflows/create_new_release.yml
    template:
      config_path: item_warehouse_website/config.yaml
      secrets_WORGARSIDE_DEV_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
  - source: gha_sync/workflows/versioned_repos
    dest: .github/workflows/
    exclude: |
      create_new_release.yml
  - source: gha_sync/configs/versioned_repos
    dest: .github/

worgarside/addon-rss-log-feed:
  - source: gha_sync/workflows/addon_repos/create_new_release.yml
    dest: .github/workflows/create_new_release.yml
    template:
      config_path: rss_log_feed/config.yaml
      secrets_WORGARSIDE_DEV_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
  - source: gha_sync/workflows/versioned_repos
    dest: .github/workflows/
    exclude: |
      create_new_release.yml
  - source: gha_sync/configs/versioned_repos
    dest: .github/

worgarside/addon-yas-209-bridge:
  - source: gha_sync/workflows/addon_repos/create_new_release.yml
    dest: .github/workflows/create_new_release.yml
    template:
      config_path: yas_209_bridge/config.yaml
      secrets_WORGARSIDE_DEV_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
  - source: gha_sync/workflows/versioned_repos
    dest: .github/workflows/
    exclude: |
      create_new_release.yml
  - source: gha_sync/configs/versioned_repos
    dest: .github/

worgarside/home-assistant-config-validator:
  - source: gha_sync/configs/versioned_repos/release-drafter.yml
    dest: .github/release-drafter.yml
