---
# yamllint disable rule:line-length
# https://github.com/rhysd/actionlint/blob/main/docs/usage.md#use-actionlint-on-github-actions

name: '"actionlint" Runner'

on:
  workflow_call:
    inputs:
      workflow-files:
        description: Space-separated list of workflow files to check
        required: false
        type: string

jobs:
  log-inputs:
    name: Log Inputs
    runs-on: ubuntu-latest
    steps:
      - name: Log Inputs
        env:
          INPUTS: ${{ toJson(inputs) }}
        run: |
          echo -e "\`\`\`json\n$INPUTS\n\`\`\`" >> "$GITHUB_STEP_SUMMARY"

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Download actionlint
        id: get-actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: Check Workflow Files
        env:
          WORKFLOW_FILES:
        run: |
          ${{ steps.get-actionlint.outputs.executable }} \
          ${{ inputs.workflow-files }} \
          -color \
          -shellcheck "" \
          -format '{{range $err := .}}::error file={{$err.Filepath}},line={{$err.Line}},col={{$err.Column}}::{{$err.Message}}%0A```%0A{{replace $err.Snippet "\\n" "%0A"}}%0A```\n{{end}}'
