---
name: Build & Publish to PyPi

on:
  workflow_call:
    inputs:
      build-branch:
        description: The branch to build from
        required: true
        type: string
      environment:
        description: The environment to deploy to
        required: true
        type: string
      python-version:
        description: The Python version to build with
        required: true
        type: string
      release-tag:
        description: The tag of the release to add the artifacts to
        required: true
        type: string
    secrets:
      gh-token:
        description: The GitHub token
        required: true
      PYPI_API_TOKEN:
        description: The PyPi API token
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.build-branch }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Poetry
        run: pipx install poetry

      - name: Build
        run: poetry build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: dist/

  add-artifacts-to-release-notes:
    name: Add Artifacts to Release Notes
    runs-on: ubuntu-latest
    needs:
      - build
    outputs:
      pr-is-draft: ${{ steps.is-pr-draft.outputs.pr-is-draft }}
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: dist/

      - name: Upload Artifacts
        run: |
          gh release upload ${{ inputs.release-tag }} dist/* \
          --clobber \
          --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.gh-token }}

      - name: Check Release PR is not Draft
        id: is-pr-draft
        env:
          GH_TOKEN: ${{ secrets.gh-token }}
        run: |
          echo "pr-is-draft=$(
            gh pr list \
            --json baseRefName,headRefName,isDraft \
            --repo ${{ github.repository }} \
            --jq '
              .[] | select(
                .baseRefName == "main"
              ) | select(
                .headRefName == "release/${{ inputs.release-tag }}"
              ) | .isDraft
            '
          )" >> "$GITHUB_OUTPUT"

      - name: Summarise Environment
        run: |
          echo -e "Environment:  \`${{ inputs.environment }}\`"
          echo -e "Build Branch: \`${{ inputs.build-branch }}\`"
          echo -e "Release Tag:  \`${{ inputs.release-tag }}\`"
          echo -e "PR is Draft:  \`${{ steps.is-pr-draft.outputs.pr-is-draft }}\`"

  publish-to-pypi:
    name: Publish to PyPI
    environment: ${{ inputs.environment }}
    if: |
      needs.add-artifacts-to-release-notes.outputs.pr-is-draft != 'true' &&
      success()
    needs:
      - add-artifacts-to-release-notes
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        continue-on-error: ${{ inputs.environment == 'development' }}
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: ${{ vars.REPOSITORY_URL }}
