---
name: '"Close Empty PR" Runner'

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      head-ref:
        description: The head branch's name (source branch)
        required: true
        type: string
      pr-number:
        description: The PR number
        required: true
        type: number

jobs:
  log-inputs:
    name: Log Inputs
    runs-on: ubuntu-latest
    steps:
      - name: Log Inputs
        if: runner.debug == '1'
        env:
          INPUTS: ${{ toJson(inputs) }}
        run: |
          echo -e "\`\`\`json\n$INPUTS\n\`\`\`" >> "${GITHUB_STEP_SUMMARY}"

  close-pr-if-empty:
    name: Close Empty PR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.head-ref }}
          fetch-depth: 0
          token: ${{ secrets.WORGARSIDE_DEV_TOKEN }}

      - name: Check for 'bot:do-not-close' label
        id: check-label
        env:
          GH_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
        run: |
          label_exists=$(
            gh pr view ${{ inputs.pr-number }} \
              --json labels \
              --jq '.labels | any(.name == "bot:do-not-close")'
          )

          echo "label-exists=$label_exists" >> "${GITHUB_OUTPUT}"

      - name: Get PR Changes
        id: get-pr-changes
        if: steps.check-label.outputs.label-exists != 'true'
        env:
          GH_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
        run: |
          total_changes=$(
            gh pr view ${{ inputs.pr-number }} \
              --json additions,deletions \
              --jq '. | add'
          )

          echo "$total_changes changes found on PR" >> "${GITHUB_STEP_SUMMARY}"

          echo "total-changes=$total_changes" >> "${GITHUB_OUTPUT}"

      - name: Close PR
        if: |
          steps.check-label.outputs.label-exists != 'true' &&
          steps.get-pr-changes.outputs.total-changes == '0'
        env:
          GH_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
        run: |
          gh pr close ${{ inputs.pr-number }} \
            --delete-branch \
            -c "This PR is empty, closing it. :no_good:"
