---
name: Create Pull Request

on:
  workflow_call:
    inputs:
      base-ref-name:
        description: The base branch's name (target branch)
        required: true
        type: string
      head-ref-name:
        description: The head branch's name (source branch)
        required: true
        type: string
      pr-title:
        description: The PR title
        required: true
        type: string
      pr-body:
        description: The PR body
        required: false
        type: string
      pr-reviewer:
        description: The PR reviewer
        required: false
        type: string
        default: ${{ github.repository_owner }}
      pr-draft:
        description: Whether the PR should be a draft
        required: false
        type: boolean
        default: true
      pr-labels:
        description: Comma-separated list of labels to apply to the PR
        required: false
        type: string
      update-pr-body-if-exists:
        description: |
          Whether to update the PR body if it already exists. Will use the `pr-body`
          input as the new body if it is provided, `--fill` otherwise.
        required: false
        type: boolean
        default: false
    secrets:
      gh-token:
        description: The GitHub token to use for the PR creation
        required: true

jobs:
  log-inputs:
    name: Log Inputs
    runs-on: ubuntu-latest
    steps:
      - name: Log Inputs
        env:
          INPUTS: ${{ toJson(inputs) }}
        run: |
          echo -e "\`\`\`json\n$INPUTS\n\`\`\`" >> $GITHUB_STEP_SUMMARY

  create-pr:
    name: Create PR
    runs-on: ubuntu-latest
    outputs:
      create-pr: ${{ steps.check-if-pr-exists.outputs.create-pr }}
      existing-pr-url: ${{ steps.check-if-pr-exists.outputs.existing-pr-url }}
    steps:
      - name: Check If PR Exists
        id: check-if-pr-exists
        env:
          GH_TOKEN: ${{ secrets.gh-token }}
        # yamllint disable rule:line-length
        run: |
          existing_pr=$(
            gh pr list \
            --repo ${{ github.repository }} \
            --json baseRefName,headRefName,title,url \
            --jq '
              .[] | select(
                .baseRefName == "${{ inputs.base-ref-name }}"
              ) | select(
                .headRefName == "${{ inputs.head-ref-name }}"
              )
            '
          )

          if [[ -z "$existing_pr" ]]; then
              echo "create-pr=true" >> $GITHUB_OUTPUT
              echo "existing-pr-url=null" >> $GITHUB_OUTPUT
          else
              pr_url=$(echo $existing_pr | jq -r '.url')

              echo -e "Existing [PR]($pr_url) found: \n\`\`\`json\n" >> $GITHUB_STEP_SUMMARY
              echo $existing_pr | jq >> $GITHUB_STEP_SUMMARY
              echo -e "\n\`\`\`" >> $GITHUB_STEP_SUMMARY

              echo "create-pr=false" >> $GITHUB_OUTPUT
              echo "existing-pr-url=$pr_url" >> $GITHUB_OUTPUT
          fi
        # yamllint enable rule:line-length

      - name: Clone Repo
        if: steps.check-if-pr-exists.outputs.create-pr == 'true'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.head-ref-name }}

      - name: Create PR
        if: steps.check-if-pr-exists.outputs.create-pr == 'true'
        env:
          GH_TOKEN: ${{ secrets.gh-token }}
           # yamllint disable-line rule:line-length
          PR_BODY_ARG: ${{ inputs.pr-body && format('--body "{0}"', inputs.pr-body) || '--fill' }}
          PR_DRAFT_ARG: ${{ inputs.pr-draft && '--draft' || '' }}
          PR_TITLE: ${{ inputs.pr-title}}
           # yamllint disable-line rule:line-length
          PR_LABELS_ARG: ${{ inputs.pr-labels && format('--label {0}', inputs.pr-labels ) || '' }}
        run: |
          gh pr create \
            --repo ${{ github.repository }} \
            --title "$PR_TITLE" \
            $PR_BODY_ARG \
            --base "${{ inputs.base-ref-name }}" \
            --head "${{ inputs.head-ref-name }}" \
            --reviewer ${{ inputs.pr-reviewer }} \
            $PR_LABELS_ARG \
            $PR_DRAFT_ARG

  update-pr:
    name: Update PR
    runs-on: ubuntu-latest
    needs: create-pr
    if: |
      inputs.update-pr-body-if-exists &&
      needs.create-pr.outputs.create-pr == 'false' &&
      needs.create-pr.outputs.existing-pr-url != 'null'
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.head-ref-name }}

      - name: Get Commits
        if: |
          !inputs.pr-body
        id: get-commits
        run: |
          git fetch --all

          git \
            fetch \
            --no-tags \
            --prune \
            --depth=1 \
            origin \
            +${{ inputs.base-ref-name }}:${{ inputs.base-ref-name }}

          git \
            fetch \
            --no-tags \
            --prune \
            --depth=1 \
            origin \
            +${{ inputs.head-ref-name }}:${{ inputs.head-ref-name }}

          git checkout ${{ inputs.head-ref-name }}

          commit_messages=$(
            git log \
              --no-merges \
              --pretty=format:"- %h | %s" \
              "${{ inputs.base-ref-name }}..${{ inputs.head-ref-name }}" |
            sed 's/--/\\-\\-/g'
          )

          commit_messages=$(echo -e "$commit_messages\n" | tac)

          echo "$commit_messages" >> $GITHUB_STEP_SUMMARY

          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "pr-body<<$EOF" >> "$GITHUB_OUTPUT"
          echo "$commit_messages" >> "$GITHUB_OUTPUT"
          echo "$EOF" >> "$GITHUB_OUTPUT"

      - name: Update PR
        env:
          GH_TOKEN: ${{ secrets.gh-token }}
        run: |
          if [ -z "${{ inputs.pr-body }}" ] || [ "${{ inputs.pr-body }}" == "--fill" ]
          then
            gh pr edit \
              ${{ needs.create-pr.outputs.existing-pr-url }} \
              --body '${{ steps.get-commits.outputs.pr-body }}'
          else
            gh pr edit \
              ${{ needs.create-pr.outputs.existing-pr-url }} \
              --body '${{ inputs.pr-body }}'
          fi
