---
name: Get Release Tag

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      branch-name:
        description: The name of the branch to extract the release tag from
        required: true
        type: string
    secrets:
      gh-token:
        description: The GitHub token to use for the PR creation
        required: true
    outputs:
      release-tag:
        description: The release tag
        value: ${{ jobs.get-release-tag.outputs.release-tag }}


jobs:

  get-release-tag:
    name: Get Release Tag
    runs-on: ubuntu-latest
    outputs:
      release-tag: ${{ steps.get-tag.outputs.release-tag }}
    steps:
      - name: Log Inputs
        if: runner.debug == '1'
        env:
          INPUTS: ${{ toJson(inputs) }}
        run: |
          echo -e "\`\`\`json\n$INPUTS\n\`\`\`" >> "$GITHUB_STEP_SUMMARY"

      - name: Get Release Tag
        id: get-tag
        env:
          BRANCH_NAME: ${{ inputs.branch-name }}
          GH_TOKEN: ${{ secrets.gh-token }}
        # yamllint disable rule:line-length
        run: |
          clean_branch_name=${BRANCH_NAME#refs/heads/}

          release_tag=$(echo "$clean_branch_name" | cut -d '/' -f2)

          if ! [[ $release_tag =~ ^[0-9]{1,2}\.[0-9]{1,4}\.[0-9]{1,4}$ ]]
          then
            release_tag=$(gh release view --json tagName --jq '.tagName') ||
              echo "Release tag is bollocks: \`$release_tag\` 😡" >> "$GITHUB_STEP_SUMMARY" && exit 1
          fi

          echo "release-tag=$release_tag" >> "$GITHUB_OUTPUT"
        # yamllint enable rule:line-length
