---
name: Get Release Tag

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      branch-name:
        description: The name of the branch to extract the release tag from
        required: false
        type: string
    outputs:
      release-tag:
        description: The release tag
        value: ${{ jobs.get-release-tag.outputs.release-tag }}

jobs:
  get-release-tag:
    name: Get Release Tag
    runs-on: ubuntu-latest
    outputs:
      release-tag: ${{ steps.get-tag.outputs.release-tag }}
    steps:
      - name: Log Inputs
        if: runner.debug == '1'
        env:
          INPUTS: ${{ toJson(inputs) }}
        run: |
          echo -e "\`\`\`json\n$INPUTS\n\`\`\`" >> "$GITHUB_STEP_SUMMARY"

      - name: Clone Repo
        uses: actions/checkout@v4
        if: |
          !inputs.branch-name
        with:
          token: ${{ secrets.WORGARSIDE_DEV_TOKEN }}

      - name: Get Release Tag
        id: get-tag
        env:
          BRANCH_NAME: ${{ inputs.branch-name }}
          GH_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
        # yamllint disable rule:line-length
        run: |
          if [[ -z "$BRANCH_NAME" ]]
          then
            release_tag=$(gh release view --json tagName --jq '.tagName')
          else
            release_tag=$(
              echo "$BRANCH_NAME" | awk -F'/' '{
                for(i=1; i<=NF; ++i) {
                  if($i ~ /^[0-9]+\.[0-9]+\.[0-9]+$/) {
                    print $i;
                  }
                }
              }'
            )
          fi

          if [[ -z "$release_tag" ]]
          then
            echo "Release tag is bollocks: \`$release_tag\` 😡" >> "$GITHUB_STEP_SUMMARY"
            exit 1
          fi

          echo "release-tag=$release_tag" >> "$GITHUB_OUTPUT"
        # yamllint enable rule:line-length
