---
name: '"Manage PR Labels" Runner'

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      base-ref:
        description: The base branch's name (target branch)
        required: true
        type: string
      event-action:
        description: The event action
        required: true
        type: string
      head-ref:
        description: The head branch's name (source branch)
        required: true
        type: string
      pr-number:
        description: The PR number
        required: true
        type: number
    secrets:
      gh-token:
        description: The GitHub token to use for the PR creation
        required: true

jobs:
  log-inputs:
    name: Log Inputs
    runs-on: ubuntu-latest
    steps:
      - name: Log Inputs
        env:
          INPUTS: ${{ toJson(inputs) }}
        run: |
          echo -e "\`\`\`json\n$INPUTS\n\`\`\`" >> $GITHUB_STEP_SUMMARY

  set-labels:
    name: Set Non-Release Labels
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: srvaroa/labeler@v1.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.gh-token }}

  set-release-label:
    name: Set Release Label
    runs-on: ubuntu-latest
    # This dependency is just to ensure that the jobs don't interfere with each other
    needs: set-labels
    if: inputs.base-ref == 'main' && startsWith(inputs.head-ref, 'release/')
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Previous Tag
        id: get-previous-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        env:
          GITHUB_TOKEN: ${{ secrets.gh-token }}
        with:
          fallback: 0.0.0

      - name: Derive Label
        id: derive-label
        # yamllint disable rule:line-length
        run: |
          new_release_number=$(echo $GITHUB_HEAD_REF | cut -d '/' -f2)
          latest_release=${{ steps.get-previous-tag.outputs.tag }}

          if ! [[ $new_release_number =~ ^[0-9]{1,2}\.[0-9]{1,4}\.[0-9]{1,4}$ ]]
          then
              echo "Release number is invalid: \`$new_release_number\`" >> $GITHUB_STEP_SUMMARY
              exit 1
          else
            echo "new-release-number=$new_release_number" >> $GITHUB_OUTPUT
            echo "latest-release=$latest_release" >> $GITHUB_OUTPUT
          fi

          if [ "${new_release_number%%.*}" != "${latest_release%%.*}" ]
          then
              echo "release-label=major" >> $GITHUB_OUTPUT
          elif [ $( cut -d '.' -f2 <<< $new_release_number) != $( cut -d '.' -f2 <<< $latest_release ) ]
          then
            echo "release-label=minor" >> $GITHUB_OUTPUT
          elif [ "${new_release_number##*.}" != "${latest_release##*.}" ]
          then
            echo "release-label=patch" >> $GITHUB_OUTPUT
          else
              echo "new_release_number is \`$new_release_number\`" >> $GITHUB_STEP_SUMMARY
              echo "latest_release is \`$latest_release\`" >> $GITHUB_STEP_SUMMARY
              exit 1
          fi
        # yamllint enable rule:line-length

      - name: Apply Label
        run: |
          gh pr edit ${{ inputs.pr-number }} \
            --add-label "${{ steps.derive-label.outputs.release-label}},release"
        env:
          GITHUB_TOKEN: ${{ secrets.gh-token }}

      - name: Summarise
        # yamllint disable rule:line-length
        run: |
          echo "# :label: Release Label Info" >> $GITHUB_STEP_SUMMARY
          echo "Release Number (derived from branch): \`${{ steps.derive-label.outputs.new-release-number }}\`" >> $GITHUB_STEP_SUMMARY
          echo "Previous Release (latest tag):  \`${{ steps.derive-label.outputs.latest-release }}\`" >> $GITHUB_STEP_SUMMARY
          echo "Release label is \`${{ steps.derive-label.outputs.release-label }}\`" >> $GITHUB_STEP_SUMMARY
        # yamllint enable rule:line-length

  validate-semver-label:
    name: Validate SemVer Label
    runs-on: ubuntu-latest
    needs: set-labels
    if: inputs.base-ref != 'main' || !startsWith(inputs.head-ref, 'release/')
    steps:
      - name: Validate SemVer Label
        uses: yogevbd/enforce-label-action@2.2.2
        with:
          # yamllint disable-line rule:line-length
          REQUIRED_LABELS_ANY: bug,dependencies,hotfix,major,minor,non-functional,patch,sync

  edit-keep-updated-label:
    name: Edit `bot:keep-updated` label
    if: |
      startsWith(inputs.event-action, 'auto_merge_') &&
      !startsWith(inputs.head-ref, 'release/')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: |
          ${{
            inputs.event-action == 'auto_merge_enabled' && 'Add' ||
            'Remove'
          }} label
        run: |
          gh pr edit ${{ inputs.pr-number }} \
            --${{
              inputs.event-action == 'auto_merge_enabled' && 'add' || 'remove'
            }}-label "bot:keep-updated" || :
        env:
          GITHUB_TOKEN: ${{ secrets.gh-token }}
