---
name: '"Manage PR Labels" Runner'

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      head-ref:
        description: The head branch's name (source branch)
        required: true
        type: string
      pr-author:
        description: The PR author's username (github.event.pull_request.user.login)
        required: true
        type: string
      pr-number:
        description: The PR number
        required: true
        type: number

env:
  ADD_LABELS: ''
  REMOVE_LABELS: ''

jobs:
  set-labels:
    name: Set Labels
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
    steps:
      - name: Log Inputs
        if: runner.debug == '1'
        env:
          INPUTS: ${{ toJson(inputs) }}
        run: |
          echo -e "\`\`\`json\n$INPUTS\n\`\`\`" >> "${GITHUB_STEP_SUMMARY}"

      - name: Clean Dependabot Labels
        if: inputs.pr-author == 'dependabot[bot]'
        run: |
          labels_to_remove=("major" "minor" "patch" "github_actions")

          pr_labels=$(
            gh pr view ${{ inputs.pr-number }} \
              --repo ${{ github.repository }} \
              --json labels \
              --jq '.labels[].name'
          )

          for label in "${labels_to_remove[@]}"; do
            if echo "$pr_labels" | grep -q "$label"; then
                echo -e "Removing \`$label\`" >> "${GITHUB_STEP_SUMMARY}"
                echo "REMOVE_LABELS=${{ env.REMOVE_LABELS }},$label" >> "${GITHUB_ENV}"
            fi
          done

      - name: Auto-Label
        uses: srvaroa/labeler@bf262763a8a8e191f5847873aecc0f29df84f957 # v1.14.0
        env:
          GITHUB_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}

      - name: Add/Remove Labels
        if: env.ADD_LABELS || env.REMOVE_LABELS
        # yamllint disable rule:line-length
        run: |
          if [[ -n "$ADD_LABELS" ]]; then
            ADD_ARG="--add-label ${ADD_LABELS#,}"
          else
            ADD_ARG=""
          fi

          if [[ -n "$REMOVE_LABELS" ]]; then
            REMOVE_ARG="--remove-label ${REMOVE_LABELS#,}"
          else
            REMOVE_ARG=""
          fi

          echo -e "\`gh pr edit ${{ inputs.pr-number }} --repo ${{ github.repository }} $ADD_ARG $REMOVE_ARG\`" >> "${GITHUB_STEP_SUMMARY}"

          gh pr edit ${{ inputs.pr-number }} \
            --repo ${{ github.repository }} \
            $ADD_ARG \
            $REMOVE_ARG
        # yamllint enable rule:line-length
