---
name: '"Manage PR Labels" Runner'

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      head-ref:
        description: The head branch's name (source branch)
        required: true
        type: string
      pr-author:
        description: The PR author's username (github.event.pull_request.user.login)
        required: true
        type: string
      pr-number:
        description: The PR number
        required: true
        type: number

env:
  ADD_LABELS: ''
  REMOVE_LABELS: ''

jobs:
  set-labels:
    name: Set Labels
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
    steps:
      - name: Log Inputs
        if: runner.debug == '1'
        env:
          INPUTS: ${{ toJson(inputs) }}
        run: |
          echo -e "\`\`\`json\n$INPUTS\n\`\`\`" >> "${GITHUB_STEP_SUMMARY}"

      - name: Clean Dependabot Labels
        if: inputs.pr-author == 'dependabot[bot]'
        run: |
          labels_to_remove=("major" "minor" "patch" "github_actions")

          pr_labels=$(
            gh pr view ${{ inputs.pr-number }} \
              --repo ${{ github.repository }} \
              --json labels \
              --jq '.labels[].name'
          )

          for label in "${labels_to_remove[@]}"; do
            if echo "$pr_labels" | grep -q "$label"; then
                echo -e "Removing \`$label\`" >> "${GITHUB_STEP_SUMMARY}"
                echo "REMOVE_LABELS=${{ env.REMOVE_LABELS }},$label" >> "${GITHUB_ENV}"
            fi
          done

      - name: Check Auto-Merge Status
        id: check-auto-merge-status
        # yamllint disable rule:line-length
        run: |
          auto_merge_status=$(
            gh pr view ${{ inputs.pr-number }} \
              --repo ${{ github.repository }} \
              --json autoMergeRequest \
              --jq '.autoMergeRequest'
          )

          echo -e "Auto-Merge Status: \`\`\`json\n$auto_merge_status\n\`\`\`" \
            >> "${GITHUB_STEP_SUMMARY}"

          if [[ -n "${auto_merge_status}" ]]; then
              echo "ADD_LABELS=${{ env.ADD_LABELS }},bot:keep-updated" >> "${GITHUB_ENV}"
          else
              echo "REMOVE_LABELS=${{ env.REMOVE_LABELS }},bot:keep-updated" >> "${GITHUB_ENV}"
          fi
        # yamllint enable rule:line-length

      - name: Auto-Label
        uses: srvaroa/labeler@v1.6.3
        env:
          GITHUB_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}

      - name: Add/Remove Labels
        if: env.ADD_LABELS || env.REMOVE_LABELS
        # yamllint disable rule:line-length
        run: |
          if [[ -n "$ADD_LABELS" ]]; then
            ADD_ARG="--add-label ${ADD_LABELS#,}"
          else
            ADD_ARG=""
          fi

          if [[ -n "$REMOVE_LABELS" ]]; then
            REMOVE_ARG="--remove-label ${REMOVE_LABELS#,}"
          else
            REMOVE_ARG=""
          fi

          echo -e "\`gh pr edit ${{ inputs.pr-number }} --repo ${{ github.repository }} $ADD_ARG $REMOVE_ARG\`" >> "${GITHUB_STEP_SUMMARY}"

          gh pr edit ${{ inputs.pr-number }} \
            --repo ${{ github.repository }} \
            $ADD_ARG \
            $REMOVE_ARG
        # yamllint enable rule:line-length

  validate-semver-label:
    name: Validate SemVer Label
    runs-on: ubuntu-latest
    steps:
      - name: Validate SemVer Label
        env:
          GITHUB_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
          REQUIRED_LABELS: bug,dependencies,hotfix,major,minor,non-functional,patch,sync
        # yamllint disable rule:line-length
        run: |
          labels=$(
            gh pr view ${{ inputs.pr-number }} \
              --repo ${{ github.repository }} \
              --json labels \
              --jq '.labels[].name'
          )

          if ! echo "$labels" | grep -qE "$(echo $REQUIRED_LABELS | tr ',' '|')"; then
            echo "No SemVer label found." >> "${GITHUB_STEP_SUMMARY}"
            echo -e "Please add one of the following labels: \`$REQUIRED_LABELS\`" >> "${GITHUB_STEP_SUMMARY}"
            echo -e "Found: \`$labels\`" >> "${GITHUB_STEP_SUMMARY}"
            exit 1
          fi
        # yamllint enable rule:line-length
