---
name: '"Manage Repo Labels" Runner'

# yamllint disable-line rule:truthy
on:
  workflow_call:

jobs:
  labeler:
    name: Manage Repo Labels
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          yaml-file: .github/repo_labels.yml
