---
name: '"Auto-Update PRs" Runner'

on:
  workflow_call:

jobs:
  autoupdate:
    name: PR Auto-Update
    runs-on: ubuntu-latest
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
          PR_FILTER: labelled
          PR_LABELS: bot:keep-updated
          MERGE_CONFLICT_ACTION: ignore
