---
name: '"Auto-Update PRs" Runner'

on:
  workflow_call:
    secrets:
      gh-token:
        description: The GitHub token to use
        required: true

jobs:
  autoupdate:
    name: PR Auto-Update
    runs-on: ubuntu-latest
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: ${{ secrets.gh-token }}
          PR_FILTER: labelled
          PR_LABELS: bot:keep-updated
