---
name: Publish Release

on:
  workflow_call:
    inputs:
      pr-merged:
        description: PR merged vs closed (github.event.pull_request.merged)
        required: true
        type: boolean
      base-ref-name:
        description: The branch the PR is merging into (github.base_ref)
        required: true
        type: string
      head-ref-name:
        description: Branch the PR is merging from (github.head_ref || github.ref_name)
        required: true
        type: string
      publish-to-pypi:
        default: false
        description: Whether to publish to PyPI
        required: false
        type: boolean
    secrets:
      gh-token:
        description: The GitHub token to use for publishing the release
        required: true
      pypi-token:
        description: The PyPI token to use for publishing the release
        required: false
      wg-dev-token:
        description: The GitHub token to use for creating the PR back to `develop`
        required: true

jobs:
  log-inputs:
    name: Log Inputs
    runs-on: ubuntu-latest
    steps:
      - name: Log Inputs
        env:
          INPUTS: ${{ toJson(inputs) }}
        run: |
          echo -e "\`\`\`json\n$INPUTS\n\`\`\`" >> "$GITHUB_STEP_SUMMARY"

  cancel-if-not-merged:
    name: Cancel Workflow if Pull Request is not merged
    runs-on: ubuntu-latest
    steps:
      - name: Check PyPi Token Provided
        if: inputs.publish-to-pypi
        # yamllint disable rule:line-length
        run: |
          if [ -z "${{ secrets.pypi-token }}" ]; then
            echo "No PyPi token provided. Cancelling workflow. :no_good:" >> "$GITHUB_STEP_SUMMARY"
            exit 1
          else
            echo "PyPi token provided. Continuing workflow. :white_check_mark:" >> "$GITHUB_STEP_SUMMARY"
          fi
        # yamllint enable rule:line-length

      - name: Check for PR Merge
        id: cancel-if-not-merged
        # yamllint disable rule:line-length
        run: |
          if [ "${{ inputs.pr-merged }}" = "false" ]; then
            echo "Pull Request was not merged. Cancelling workflow. :no_good:" >> "$GITHUB_STEP_SUMMARY"
            echo "cancelling=true" >> $GITHUB_ENV
            gh run cancel ${{ github.run_id }} --repo ${{ github.repository }}
          else
            echo "Pull Request was merged. Continuing workflow. :white_check_mark:" >> "$GITHUB_STEP_SUMMARY"
            echo "cancelling=false" >> $GITHUB_ENV
          fi
        # yamllint enable rule:line-length
        env:
          GITHUB_TOKEN: ${{ secrets.gh-token }}

      # Give the cancel command up to 2 mins to take effect, otherwise fail the workflow
      - name: Wait for workflow to be cancelled
        if: steps.cancel-if-not-merged.outputs.cancelling == 'true'
        run: |
          sleep 120
          exit 1
        env:
          GITHUB_TOKEN: ${{ secrets.gh-token }}

  get-release-tag:
    name: Get Release Tag
    uses: ./.github/workflows/__get_release_tag.yml
    needs:
      - cancel-if-not-merged
    with:
      branch-name: ${{ inputs.head-ref-name }}

  publish-release-notes:
    name: Publish Release Notes
    runs-on: ubuntu-latest
    needs:
      - get-release-tag
    env:
      GITHUB_TOKEN: ${{ secrets.gh-token }}
    permissions:
      contents: write
    steps:
      - name: Point Release at `${{ inputs.base-ref-name }}`
        run: |
          gh release edit ${{ needs.get-release-tag.outputs.release-tag }} \
           --target ${{ inputs.base-ref-name }} \
           --repo ${{ github.repository }}

      - name: Publish Release Notes
        run: |
          gh release edit ${{ needs.get-release-tag.outputs.release-tag }} \
            --draft=false \
            --repo ${{ github.repository }}

  publish-to-pypi:
    name: Publish to PyPi
    if: inputs.publish-to-pypi
    uses: ./.github/workflows/__build_and_publish.yml
    needs:
      - get-release-tag
    with:
      build-branch: ${{ inputs.head-ref-name }}
      environment: production
      python-version: '3.11'
      release-tag: ${{ needs.get-release-tag.outputs.release-tag }}
    secrets:
      gh-token: ${{ secrets.wg-dev-token }}
      pypi-token: ${{ secrets.pypi-token }}

  create-pr-back-to-develop:
    name: Create PR back to `develop`
    needs:
      - get-release-tag
      - publish-release-notes
    # yamllint disable rule:line-length
    uses: worgarside/github-config-files/.github/workflows/__create_pull_request.yml@main
    with:
      base-ref-name: develop
      head-ref-name: ${{ inputs.head-ref-name }}
      pr-title: Merge `${{ inputs.head-ref-name }}` back into `develop`
      pr-draft: false
      pr-labels: bot:delete-on-merge,non-functional,skip-changelog
    secrets:
      gh-token: ${{ secrets.wg-dev-token }}
