---
name: '"Set PR Auto Merge" Runner'

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      head-ref:
        description: >
          The head branch's name (source branch): `github.event.pull_request.head.ref`
        required: true
        type: string
      pr-html-url:
        description: 'The PRs HTML URL: `github.event.pull_request.html_url`'
        required: true
        type: string
      pr-number:
        description: 'The PRs number: `github.event.pull_request.number`'
        required: true
        type: number
      pr-title:
        description: 'The PRs title: `github.event.pull_request.title`'
        required: true
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}

jobs:
  set-auto-merge:
    name: Set Auto Merge
    runs-on: ubuntu-latest
    steps:
      - name: Log Inputs
        if: runner.debug == '1'
        env:
          INPUTS: ${{ toJson(inputs) }}
        run: |
          echo -e "\`\`\`json\n$INPUTS\n\`\`\`" >> "$GITHUB_STEP_SUMMARY"

      - name: Set Auto-Merge on PR
        if: github.repository != 'worgarside/github-config-files'
        run: |
          gh pr merge "${{ inputs.pr-html-url }}" \
            --delete-branch \
            --squash \
            --auto

      - name: Set Auto-Merge on PR (GHCF)
        if: github.repository == 'worgarside/github-config-files'
        env:
          PR_TITLE: ${{ inputs.pr-title }}
        run: |
          gh pr merge "${{ inputs.pr-html-url }}" \
            --delete-branch \
            --squash \
            --auto \
            --subject "$PR_TITLE" \
            --body "${{ github.repository }}#${{ inputs.pr-number }}"
