---
name: '"SonarCloud" Runner'

on:
  workflow_call:
    inputs:
      branch:
        description: The branch to scan
        required: true
        type: string
      coverage-artifact:
        description: The name of the coverage artifact to download
        required: false
        type: string

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Log Inputs
        if: runner.debug == '1'
        env:
          INPUTS: ${{ toJson(inputs) }}
        run: |
          echo -e "\`\`\`json\n$INPUTS\n\`\`\`" >> "$GITHUB_STEP_SUMMARY"

      - name: Clone Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}

      - name: Download Coverage Report
        if: inputs.coverage-artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.coverage-artifact }}
        continue-on-error: true

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
