---
name: SonarCloud

on:
  workflow_call:
    inputs:
      branch:
        description: The branch to scan
        required: true
        type: string
      coverage-artifact:
        description: The name of the coverage artifact to download
        required: false
        type: string
    secrets:
      sonar-token:
        description: The SonarCloud token
        required: true

jobs:
  log-inputs:
    name: Log Inputs
    runs-on: ubuntu-latest
    steps:
      - name: Log Inputs
        env:
          INPUTS: ${{ toJson(inputs) }}
        run: |
          echo -e "\`\`\`json\n$INPUTS\n\`\`\`" >> "$GITHUB_STEP_SUMMARY"

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}

      - name: Download Coverage Report
        if: inputs.coverage-artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.coverage-artifact }}

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.sonar-token }}
