---
name: Manage Repo Labels

on:
  push:
    branches:
      - develop
      - main
    paths:
      - .github/repo_labels.yml
      - .github/workflows/manage_repo_labels.yml

jobs:
  manage_repo_labels:
    name: Manage Repo Labels
    uses: ./.github/workflows/__manage_repo_labels.yml
