---
name: Manage PR Labels

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - auto_merge_enabled
      - auto_merge_disabled

concurrency:
  # yamllint disable-line rule:line-length
  group: manage-labels-${{ github.event.pull_request.number }}-${{ github.event.action }}
  cancel-in-progress: true

jobs:
  manage-pr-labels:
    name: Manage PR Labels
    uses: ./.github/workflows/__manage_pr_labels.yml
    with:
      head-ref: ${{ github.head_ref }}
      pr-author: ${{ github.event.pull_request.user.login }}
      pr-number: ${{ github.event.pull_request.number }}
    secrets: inherit
