---
name: Manage PR Labels

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
      - auto_merge_enabled
      - auto_merge_disabled

concurrency:
  # yamllint disable-line rule:line-length
  group: manage-labels-${{ github.event.pull_request.number }}-${{ github.event.action }}
  cancel-in-progress: true

jobs:
  manage_pr_labels:
    name: Manage PR Labels
    uses: .github/workflows/__manage_pr_labels.yml
    inputs:
      base-ref: ${{ github.base_ref }}
      event-action: ${{ github.event.action }}
      head-ref: ${{ github.head_ref }}
      pr-number: ${{ github.event.pull_request.number }}
    secrets:
      gh-token: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
