---
name: Auto-Update PRs

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
      - develop

jobs:
  autoupdate:
    name: PR Auto-Update
    uses: ./.github/workflows/__pr_autoupdate.yml
    secrets: inherit
