---
name: Auto-Update PRs

on:
  pull_request:
    types:
      - labeled
  push:
    branches:
      - main

jobs:
  autoupdate:
    name: PR Auto-Update
    if: github.event_name == 'push' || github.event.label.name == 'bot:keep-updated'
    uses: ./.github/workflows/__pr_autoupdate.yml
    secrets: inherit
