---
name: PR Cleanup

on:
  pull_request:
    types:
      - closed
      - opened
      - labeled

jobs:
  pr-cleanup:
    name: PR Cleanup
    uses: ./.github/workflows/__pr_cleanup.yml
    with:
      head-ref: ${{ github.head_ref }}
      pr-label-names: join(github.event.pull_request.labels.*.name)
      pr-merged: ${{ github.event.pull_request.merged }}
      pr-number: ${{ github.event.pull_request.number }}
    secrets:
      gh-token: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
