---
name: Reject Stale Deployments

on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *

jobs:
  reject-deployments:
    name: Reject Stale Deployments
    runs-on:
      - self-hosted
      - linux
      - x64
      - cc
      - iac
      - opentofu
    steps:
      - name: Clone Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true
          cache-local-path: ${{ github.workspace }}/.uv-cache
          python-version: '3.11'

      - name: Install Dependencies
        run: uv sync --locked --all-groups --no-build

      - name: Reject Deployments
        env:
          LOG_LEVEL: ${{ runner.debug == '1' && 'DEBUG' || 'INFO' }}
          GH_TOKEN: ${{ secrets.WORGARSIDE_TOKEN }}
        run: uv run --no-sync python utilities/reject_stale_deployments/reject_deployments.py
