---
name: Reject Stale Deployments

on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *

jobs:
  reject-deployments:
    name: Reject Stale Deployments
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true
          cache-local-path: ${{ github.workspace }}/.uv-cache
          python-version: '3.11'

      - name: Install Dependencies
        run: uv sync --locked --all-groups --no-build

      - name: Reject Deployments
        env:
          LOG_LEVEL: ${{ runner.debug == '1' && 'DEBUG' || 'INFO' }}
          GH_TOKEN: ${{ secrets.WORGARSIDE_TOKEN }}
        run: uv run --no-sync python utilities/reject_stale_deployments/reject_deployments.py
