---
name: Run SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  run-sonarcloud-scan:
    name: Run SonarCloud Scan
    uses: ./.github/workflows/__sonarcloud.yml
    with:
      branch: ${{ github.ref }}
    secrets: inherit
