---
name: Run SonarCloud Scan

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  run-sonarcloud-scan:
    name: Run SonarCloud Scan
    uses: ./.github/workflows/__sonarcloud.yml
    with:
      branch: ${{ github.ref }}
    secrets: inherit
