---
name: Set PR Auto Merge

  # yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - ready_for_review

concurrency:
  group: set-auto-merge-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  set_auto_merge:
    name: Set PR Auto Merge
    uses: ./.github/workflows/__set_pr_auto_merge.yml
    inputs:
      head-ref: ${{ github.head_ref }}
      pr-html-url: ${{ github.event.pull_request.html_url }}
      pr-is-draft: ${{ github.event.pull_request.draft }}
      pr-number: ${{ github.event.pull_request.number }}
      pr-title: ${{ github.event.pull_request.title }}
    secrets:
      gh-token: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
