---
name: Auto-Create PR

on:
  push:
    branches:
      - feature/*
      - bugfix/*

jobs:
  create-pr:
    name: Create PR
    # yamllint disable-line rule:line-length
    uses: worgarside/github-config-files/.github/workflows/create_pr.yml@bugfix/escape-chars-in-pr-titles
    with:
      base-ref-name: ${{ github.event.repository.default_branch }}
      head-ref-name: ${{ github.ref_name }}
      pr-title: ${{ github.event.head_commit.message }}
      pr-draft: true
    secrets:
      gh-token: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
