---
name: Auto-Merge Pre-Commit Update PR
on:
  pull_request:
    types:
      - labeled
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          MERGE_LABELS: auto-merge
          MERGE_FILTER_AUTHOR: worgarside
          MERGE_DELETE_BRANCH: true
          MERGE_ERROR_FAIL: true
          UPDATE_METHOD: rebase
          MERGE_RETRIES: 10
          MERGE_RETRY_SLEEP: 15000
