---
name: Create New Release

on:
  workflow_call:
    inputs:
      draft-release:
        description: Whether to draft a release
        required: false
        default: true
        type: boolean
      update-pyproject-toml:
        description: Update the pyproject.toml version
        required: false
        default: true
        type: boolean
    secrets:
      gh-token:
        description: The GitHub token to use for the PR creation
        required: true

jobs:
  log-inputs:
    name: Log Inputs
    runs-on: ubuntu-latest
    steps:
      - name: Log Inputs
        env:
          INPUTS: ${{ toJson(inputs) }}
        run: |
          echo -e "\`\`\`json\n$INPUTS\n\`\`\`" >> $GITHUB_STEP_SUMMARY

  check-for-existing-release:
    name: Check for Existing Release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.gh-token }}
    outputs:
      pending-release-tag: ${{ steps.get-release-branch.outputs.pending-release-tag }}
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Release Branch(es)
        id: get-release-branch
        # yamllint disable rule:line-length
        run: |
          git_output=$(git branch -r --list 'origin/release/*')

          echo -e "\`\`\`bash\n> git branch -r --list 'origin/release/*'\n$git_output\n\`\`\`\n---\n" >> "$GITHUB_STEP_SUMMARY"

          if [[ -z "$git_output" ]]; then
            echo "No branches found :kissing::ok_hand:" >> "$GITHUB_STEP_SUMMARY"
            echo "pending-release-tag=null" >> "$GITHUB_OUTPUT"
          elif [[ $(echo "$git_output" | wc -l) -gt 1 ]]; then
            echo -e "More than 1 release branch found: \n\`\`\`\n$git_output\n\`\`\`" >> "$GITHUB_STEP_SUMMARY"
            exit 1
          else
            pending_release_tag=${git_output#  origin/release/}
            echo -e "1 branch found: \`release/$pending_release_tag\`" >> "$GITHUB_STEP_SUMMARY"
            echo "pending-release-tag=$pending_release_tag" >> "$GITHUB_OUTPUT"
          fi
        # yamllint enable rule:line-length

  derive-release-branch-name:
    name: Derive Release Branch Name
    runs-on: ubuntu-latest
    needs: check-for-existing-release
    env:
      GH_TOKEN: ${{ secrets.gh-token }}
    outputs:
      release-branch: ${{ steps.get-release-version.outputs.release-branch }}
      release-tag: ${{ steps.get-release-version.outputs.release-tag }}
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Get SemVer Label
        id: get-semver-label
        # yamllint disable rule:line-length
        run: |
          latest_release=$(gh release view --json publishedAt,tagName) ||
            latest_release='{"publishedAt": "1970-01-01T00:00:00Z", "tagName": "0.0.0"}'

          echo -e "\`\`\`bash\n> gh release view --json publishedAt,tagName\n${{ toJson('$latest_release') }}\n\`\`\`\n---\n" >> "$GITHUB_STEP_SUMMARY"

          latest_release_tag=$(echo "$latest_release" | jq -r '.tagName')
          latest_release_date=$(echo "$latest_release" | jq -r '.publishedAt')

          echo "\`latest_release_tag\`: \`$latest_release_tag\`" >> $GITHUB_STEP_SUMMARY
          echo "\`latest_release_date\`: \`$latest_release_date\`" >> $GITHUB_STEP_SUMMARY

          echo "latest-release-tag=$latest_release_tag" >> "$GITHUB_OUTPUT"

          all_prs=$(
            gh pr list \
            --state merged \
            --author worgarside-dev \
            --json baseRefName,headRefName,labels,number,mergedAt,title,url \
            --limit 100 \
            --jq '
                .[] |
                select(
                  (.baseRefName == "develop") and
                  (.headRefName != "repo-sync/github-config-files/default") and
                  (
                    .labels |
                    map(.name) |
                    index("skip-changelog") |
                    not
                  ) and
                  (
                    .labels |
                    map(.name) |
                    index("non-functional") |
                    not
                  )
                )
            '
          )

          echo -e "All PRs\n\`\`\`json\n$all_prs\n\`\`\`\n---\n" >> $GITHUB_STEP_SUMMARY

          new_prs=$(
            echo "$all_prs" |
            jq -r --arg latest_release_date "$latest_release_date" '
              select(.mergedAt > $latest_release_date)
            '
          )

          echo -e "New PRs\n\`\`\`json\n$new_prs\n\`\`\`\n---\n" >> $GITHUB_STEP_SUMMARY

          new_pr_labels=$(
            echo "$new_prs" |
            jq -r '
              .labels[] |
              select(
                .name == "major" or
                .name == "minor" or
                .name == "patch" or
                .name == "bug"
              ) |
              .name
            '
          )

          echo -e "New PR labels:\n\`\`\`\n$new_pr_labels\n\`\`\`" >> $GITHUB_STEP_SUMMARY

          if echo "$new_pr_labels" | grep -q 'major' ||
          [ "$new_pr_labels" = "major" ]
          then
              semver_label="major"
          elif echo "$new_pr_labels" | grep -q 'minor' ||
          [  "$new_pr_labels" = "minor" ]
          then
              semver_label="minor"
          elif echo "$new_pr_labels" | grep -q 'patch' ||
          echo "$new_pr_labels" | grep -q 'bug' ||
          [ "$new_pr_labels" = "patch" ] ||
          [ "$new_pr_labels" = "bug" ]
          then
              semver_label="patch"
          else
              echo "No matching label found" >> $GITHUB_STEP_SUMMARY
              echo -e "\`\`\`\n$new_pr_labels\n\`\`\`" >> $GITHUB_STEP_SUMMARY
              exit 1
          fi

          echo "semver-label=$semver_label" >> "$GITHUB_OUTPUT"
          echo "\`semver_label\`: \`$semver_label\`" >> $GITHUB_STEP_SUMMARY
        # yamllint enable rule:line-length

      - name: Get Release Branch Name
        id: get-release-version
        # yamllint disable rule:line-length
        run: |
          IFS=. read major minor patch <<< "${{ steps.get-semver-label.outputs.latest-release-tag }}"

          echo "Major: \`$major\`" >> "$GITHUB_STEP_SUMMARY"
          echo "Minor: \`$minor\`" >> "$GITHUB_STEP_SUMMARY"
          echo "Patch: \`$patch\`" >> "$GITHUB_STEP_SUMMARY"

          case "${{ steps.get-semver-label.outputs.semver-label }}" in
            major)
              echo "SemVer label is major" >> "$GITHUB_STEP_SUMMARY"
              major=$(expr $major + 1)
              echo "Incremented major to $major" >> "$GITHUB_STEP_SUMMARY"
              minor=0
              patch=0
              ;;
            minor)
              echo "SemVer label is minor" >> "$GITHUB_STEP_SUMMARY"
              minor=$(expr $minor + 1)
              echo "Incremented minor to $minor" >> "$GITHUB_STEP_SUMMARY"
              patch=0
              ;;
            patch)
              echo "SemVer label is patch" >> "$GITHUB_STEP_SUMMARY"
              patch=$(expr $patch + 1)
              echo "Incremented patch to $patch" >> "$GITHUB_STEP_SUMMARY"
              ;;
          esac

          release_tag="$major.$minor.$patch"

          echo "release-tag=$release_tag" >> "$GITHUB_OUTPUT"
          echo "release-branch=release/$release_tag" >> "$GITHUB_OUTPUT"
          echo "\`release-tag\`: \`$release_tag\`" >> "$GITHUB_STEP_SUMMARY"
          echo "\`release-branch\`: \`release/$release_tag\`" >> "$GITHUB_STEP_SUMMARY"
        # yamllint enable rule:line-length

  delete-pending-release:
    name: Delete Pending Release
    runs-on: ubuntu-latest
    needs:
      - check-for-existing-release
      - derive-release-branch-name
    env:
      GH_TOKEN: ${{ secrets.gh-token }}
    if: |
      needs.check-for-existing-release.outputs.pending-release-tag !=
      'null' &&
      needs.check-for-existing-release.outputs.pending-release-tag !=
      needs.derive-release-branch-name.outputs.release-tag
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Delete Release Branch
        run: |
          git push origin --delete \
            release/${{ needs.check-for-existing-release.outputs.pending-release-tag }}


  # If nothing has failed, and there is no pending release, or the pending release is
  # not the same as the release we want to create, then create the new release branch
  create-release-branch:
    name: Create Release Branch
    runs-on: ubuntu-latest
    needs:
      - check-for-existing-release
      - derive-release-branch-name
      - delete-pending-release
    if: |
      always() && !cancelled() &&
      needs.check-for-existing-release.result == 'success' &&
      needs.derive-release-branch-name.result == 'success' &&
      (
        needs.check-for-existing-release.outputs.pending-release-tag ==
        'null' ||
        needs.check-for-existing-release.outputs.pending-release-tag !=
        needs.derive-release-branch-name.outputs.release-tag
      )
    env:
      GH_TOKEN: ${{ secrets.gh-token }}
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Create Release Branch
        run: |
          git config --global user.name "worgarside-dev"
          git config --global user.email "worgarside.dev@gmail.com"
          git checkout -b \
            release/${{ needs.derive-release-branch-name.outputs.release-tag }}

      - name: Update `pyproject.toml` Version
        if: inputs.update-pyproject-toml
        continue-on-error: true
        # yamllint disable rule:line-length
        run: |
          sed -i "s/^version = .*/version = \"${{ needs.derive-release-branch-name.outputs.release-tag }}\"/" pyproject.toml
          git add pyproject.toml
          git commit -m "Bump version to ${{ needs.derive-release-branch-name.outputs.release-tag }}" --allow-empty
        # yamllint enable rule:line-length

      - name: Push Branch
        run: |
          git push origin \
            release/${{ needs.derive-release-branch-name.outputs.release-tag }}

  draft-release:
    if: |
      always() &&
      inputs.draft-release &&
      needs.derive-release-branch-name.result == 'success' &&
      (
        needs.create-release-branch.result == 'success' ||
        needs.create-release-branch.result == 'skipped'
      )
    name: Draft Release
    uses: ./.github/workflows/draft_release.yml
    needs:
      - derive-release-branch-name
      - create-release-branch
    with:
      base-ref-name: main
      head-ref-name: ${{ needs.derive-release-branch-name.outputs.release-branch }}
    secrets:
      gh-token: ${{ secrets.gh-token }}
