---
name: Pre-Commit auto-update
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Pre-Commit
        run: pip install pre-commit
      - name: Run `pre-commit autoupdate`
        run: pre-commit autoupdate
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          add_options: '.pre-commit-config.yaml'
          commit_message: Auto-update Pre-Commit hooks
