---
name: Publish Release Notes

on:
  workflow_call:
    inputs:
      pr-merged:
        description: PR merged vs closed (github.event.pull_request.merged)
        required: true
        type: boolean
      base-ref-name:
        description: The branch the PR is merging into (github.base_ref)
        required: true
        type: string
      head-ref-name:
        description: Branch the PR is merging from (github.head_ref || github.ref_name)
        required: true
        type: string
    secrets:
      gh-token:
        description: The GitHub token to use for publishing the release
        required: true
      wg-dev-token:
        description: The GitHub token to use for creating the PR back to `develop`
        required: true

jobs:
  log-inputs:
    name: Log Inputs
    runs-on: ubuntu-latest
    steps:
      - name: Log Inputs
        env:
          INPUTS: ${{ toJson(inputs) }}
        run: |
          echo -e "\`\`\`json\n$INPUTS\n\`\`\`" >> "$GITHUB_STEP_SUMMARY"

  cancel-if-not-merged:
    name: Cancel Workflow if Pull Request is not merged
    runs-on: ubuntu-latest
    steps:
      - name: Check for PR Merge
        id: cancel-if-not-merged
        # yamllint disable rule:line-length
        run: |
          if [ "${{ inputs.pr-merged }}" = "false" ]; then
            echo "Pull Request was not merged. Cancelling workflow. :no_good:" >> "$GITHUB_STEP_SUMMARY"
            echo "cancelling=true" >> $GITHUB_ENV
            gh run cancel ${{ github.run_id }} --repo ${{ github.repository }}
          else
            echo "Pull Request was merged. Continuing workflow. :white_check_mark:" >> "$GITHUB_STEP_SUMMARY"
            echo "cancelling=false" >> $GITHUB_ENV
          fi
        # yamllint enable rule:line-length
        env:
          GITHUB_TOKEN: ${{ secrets.gh-token }}

      # Give the cancel command up to 2 mins to take effect, otherwise fail the workflow
      - name: Wait for workflow to be cancelled
        if: ${{ steps.cancel-if-not-merged.outputs.cancelling == 'true' }}
        run: |
          sleep 120
          exit 1
        env:
          GITHUB_TOKEN: ${{ secrets.gh-token }}

  get-release-tag:
    name: Get Release Tag
    uses: ./.github/workflows/get_release_tag.yml
    needs:
      - cancel-if-not-merged
    with:
      branch-name: ${{ inputs.head-ref-name }}

  publish-release-notes:
    name: Publish Release Notes
    runs-on: ubuntu-latest
    needs:
      - get-release-tag
    env:
      GITHUB_TOKEN: ${{ secrets.gh-token }}
    permissions:
      contents: write
    steps:
      - name: Point Release at `${{ inputs.base-ref-name }}`
        run: |
          gh release edit ${{ needs.get-release-tag.outputs.release-tag }} \
           --target ${{ inputs.base-ref-name }} \
           --repo ${{ github.repository }}

      - name: Publish Release Notes
        run: |
          gh release edit ${{ needs.get-release-tag.outputs.release-tag }} \
            --draft=false \
            --repo ${{ github.repository }}

  create-pr-back-to-develop:
    name: Create PR back to `develop`
    needs:
      - get-release-tag
      - publish-release-notes
    uses: ./.github/workflows/create_pr.yml
    with:
      base-ref-name: develop
      head-ref-name: ${{ inputs.head-ref-name }}
      pr-title: Merge `${{ inputs.head-ref-name }}` back into `develop`
      pr-draft: true
      pr-labels: bot:delete-on-merge,non-functional,skip-changelog
    secrets:
      gh-token: ${{ secrets.wg-dev-token }}
