---
name: Run SonarCloud Scan

on:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  run_sonarcloud_scan:
    name: Run SonarCloud Scan
    uses: ./.github/workflows/sonarcloud.yml
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
