---
name: Sync Files

# yamllint disable-line rule:truthy
on:
  push:

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Run GitHub File Sync
        if: github.event.head_commit.message != 'Auto-update Pre-Commit hooks'
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          SKIP_PR: false
          COMMIT_PREFIX: ''
          ORIGINAL_MESSAGE: true
          PR_LABELS: sync
          COMMIT_AS_PR_TITLE: true
