---
name: Sync Repos

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    paths:
      - .github/CODEOWNERS
      - .github/dependabot.yml
      - .github/labeler.yml
      - .github/repo_labels.yml
      - .github/workflows/sync.yml
      - gha_sync/**
      - .gitignore
      - .pylintrc
      - .yamllint

  workflow_dispatch:

concurrency:
  group: sync
  cancel-in-progress: true

jobs:
  sync:
    name: Sync Repos
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Run GitHub File Sync
        if: github.event.head_commit.message != 'Auto-update Pre-Commit hooks'
        id: sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
          CONFIG_PATH: gha_sync/config.yml
          COMMIT_EACH_FILE: false
          SKIP_PR: false
          COMMIT_PREFIX: ''
          ORIGINAL_MESSAGE: true
          COMMIT_AS_PR_TITLE: true
          REVIEWERS: worgarside
          PR_LABELS: |
            sync
            bot:keep-updated

      - name: Enable Auto-Merge on PRs
        if: github.event.head_commit.message != 'Auto-update Pre-Commit hooks'
        env:
          GH_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
        # yamllint disable rule:line-length
        run: |
          arr=$(echo '${{ steps.sync.outputs.pull_request_urls }}' | jq -c -r '.[]')
          for url in $arr; do
              pr_status=$(gh pr view "$url" --json state -q '.state')
              if [[ "$pr_status" == "OPEN" ]]; then
                  gh pr merge --delete-branch --squash --auto "$url"
              else
                  IFS='/' read -ra ADDR <<< "$url"
                  repo_owner="${ADDR[-4]}"
                  repo_name="${ADDR[-3]}"
                  pr_number="${ADDR[-1]}"

                  echo -e "PR $repo_owner/$repo_name#$pr_number is \`${pr_status,,}\`; not setting auto merge." >> $GITHUB_STEP_SUMMARY
              fi
          done
        # yamllint enable rule:line-length

      - name: Record Updated PRs

        env:
          GH_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
          URL_LIST: ${{ join(fromJson(steps.sync.outputs.pull_request_urls)) }}
        run: |
          url_list_formatted=$(echo "$URL_LIST" | sed 's/,/\n- /g')
          output="# Repo Sync PRs

          - $url_list_formatted"

          echo -e "${output}" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ github.actor }}" == "workflow_dispatch" ]]; then
            gh pr comment \
              "$(
                gh pr list \
                  --base main \
                  --state merged \
                  --limit 1 \
                  --json url  |
                    jq -r '.[].url'
              )" \
              --body "$output"
          fi
