---
name: Sync Repos

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: sync
  cancel-in-progress: true

jobs:
  sync:
    name: Sync Repos
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Run GitHub File Sync
        if: github.event.head_commit.message != 'Auto-update Pre-Commit hooks'
        id: sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
          SKIP_PR: false
          COMMIT_PREFIX: ''
          ORIGINAL_MESSAGE: true
          COMMIT_AS_PR_TITLE: true
          REVIEWERS: worgarside
          PR_LABELS: |
            sync
            keep-updated

      - name: Summarise
        if: github.event.head_commit.message != 'Auto-update Pre-Commit hooks'
        # yamllint disable-line rule:line-length
        run: echo -e "Pull Request URLs:\n\`\`\`json\n${{ toJson(steps.sync.outputs.pull_request_urls) }}\n\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Enable Auto-Merge on PRs
        if: github.event.head_commit.message != 'Auto-update Pre-Commit hooks'
        env:
          GH_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
        run: |
          arr=$(echo '${{ steps.sync.outputs.pull_request_urls }}' | jq -c -r '.[]')
          for url in $arr; do
              gh pr merge --delete-branch --squash --auto "$url"
          done
